# Generated by Django 6.0.6 on 2026-07-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='service_interest',
            field=models.CharField(blank=True, choices=[('social-media-posts', 'Social Media Posts'), ('travel-flyers', 'Travel Flyers'), ('political-posters', 'Political Posters'), ('general-flyers', 'General Flyers'), ('mockups', 'Mockups'), ('logos', 'Logos')], max_length=100, null=True),
        ),
    ]
